data:
  batch_size: 1
  channels: 1
  diameter: 0.4745
  im_size: 256
  length: 10000
  name: DiskDistributedEllipsesDataset
  num_n_ellipse: 140
  validation:
    num_images: 10
device: cuda
model:
  attention_resolutions: '16'
  dropout: 0.0
  image_size: 256
  in_channels: 1
  learn_sigma: false
  num_channels: 256
  num_head_channels: 64
  num_heads: 4
  num_heads_upsample: -1
  num_res_blocks: 1
  out_channels: 1
  resamp_with_conv: true
  resblock_updown: true
  type: openai
  use_fp16: false
  use_new_attention_order: false
  use_scale_shift_norm: true
  var_type: fixedsmall
sampling:
  batch_size: 1
  eps: 0.001
  travel_length: 1
  travel_repeat: 1
sde:
  beta_max: 0.02
  beta_min: 0.0001
  beta_schedule: linear
  num_steps: 1000
  type: ddpm
seed: 10
training:
  ema_decay: 0.999
  ema_warm_start_steps: 400
  epochs: 100
  log_freq: 25
  lr: 1e-4
  save_model_every_n_epoch: 25
validation:
  batch_size: 6
  eps: 1e-3
  num_steps: 100
  sample_freq: 0
  snr: 0.05
