data:
    dataset: "aapm"
    image_size: 256
    channels: 1
    num_workers: 32
    rescaled: false
    model_path: checkpoint/AAPM/vp/AAPM256_1M.pt

model:
    type: "openai"
    in_channels: 1
    out_channels: 1
    num_channels: 256
    num_heads: 4
    num_res_blocks: 1
    attention_resolutions: "16"
    dropout: 0.0
    resamp_with_conv: true
    learn_sigma: true
    use_scale_shift_norm: true
    use_fp16: false
    resblock_updown: true
    num_heads_upsample: -1
    var_type: 'fixedsmall'
    num_head_channels: 64
    image_size: 256
    class_cond: false
    use_new_attention_order: false

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 1
 
time_travel:
    T_sampling: 250
    travel_length: 1 
    travel_repeat: 1 